name: PHP Composer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
      
    - name: phpcsfixer
      run: ./vendor/bin/php-cs-fixer fix --dry-run --config=php_cs.dist
      
    - name: phpstan
      run: ./vendor/bin/phpstan analyse src public tests --memory-limit=-1
      
    - name: unitTests
      run: php -dxdebug.mode=coverage vendor/bin/phpunit tests/unitTests --testdox --coverage-clover=report/unitTests/coverage-report.clover --log-junit=report/unitTests/report.xml
      
    - name: integrationTests
      run: php -dxdebug.mode=coverage vendor/bin/phpunit tests/integrationTests --testdox --coverage-clover=report/integrationTests/coverage-report.clover --log-junit=report/integrationTests/report.xml
      
      
    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
